<?php

function gumi_register_help( $path, $arg )
{
    switch ( $path )
    {
        case 'admin/help#gumi_register':
        {
            return( '<p>' . t('This module allows users who login with e-mail addresses to authenticate off an external system.') . '</p>' );
        }
    }
}

function gumi_register_form_user_register_form_alter(&$form, $form_state ) {
	
	unset($form['links']);
	//print_r($form);exit;
	$tmp=array_merge($form['#validate'],array('gumi_register_validate'));
	$form['#validate']=$tmp;
	
}

function gumi_register_validate($form, &$form_state ) {
	global $_POST;
	
	$test=validate_external_user($_POST["mail"],$_POST["pass"]["pass1"]);
	//print_r($test);exit;
	if(isset($test->token) && $test->token) {
		form_set_error('name', t('An account using this email exists'));
	} else {
		$form_state["input"]["name"]=$form["account"]["mail"]["#value"];
		$form_state["values"]["name"]=$form["account"]["mail"]["#value"];
		$form_state["complete form"]["account"]["name"]["#value"]=$form["account"]["mail"]["#value"];
		$form["account"]["name"]["#value"]=$form["account"]["mail"]["#value"];
	}
	//print_r($_POST);	exit;
}

function gumi_register_user_insert( &$edit, &$account, $category = null ) {
	global $_POST, $_SESSION;
	//print_r($_POST);exit;
	//print_r($account);exit;
	$rs=register_external_user($account->mail,$_POST["pass"]["pass1"]);
	 user_set_authmaps($account, array(
      "authname_gumi_auth" => $account->mail,
    ));
    
    // l'utilisateur se connectant automatiquement, il fat récupérer le token gumi
    $rs=validate_external_user( $account->mail,$_POST["pass"]["pass1"]);
    
    if (isset($rs->token))  {
			
        $_SESSION["token_gumi"]=$rs->token;
        setrawcookie("token_gumi",$rs->token,time()+(24*36));
	}

}


function register_external_user( $email, $password ) {
	
	$c=curl_init();
	
	$data=array(
		"secretKey"=>generate_uuid(),
		"emailAddress"=>$email,
		"passwordHash"=>hash("sha256",$password),
	);
	
	$output="";
	
	
	curl_setopt($c,CURLOPT_URL,"http://ec2-34-251-110-19.eu-west-1.compute.amazonaws.com/website/register");
	curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($c, CURLOPT_POST, 1);
	curl_setopt($c, CURLOPT_CUSTOMREQUEST, "POST");
	
	curl_setopt($c,CURLOPT_HTTPHEADER, array(
		"Accept: application/json",
		"Content-Type: application/json",
		
	));
	curl_setopt($c, CURLOPT_POSTFIELDS, json_encode($data));
	
	$output = json_decode(curl_exec($c));
	
	return $output;
}

