<?php

function gumi_init() {
	global $user, $_SESSION, $post_num;

	 

}



function gumi_views_query_alter(&$view,&$query) {
	global $user;
	
	if($view->name=="user_gumi") {
		
		if(is_object($user) && !empty($user->uid)) {
			$query->where[1]["conditions"][1]["operator"]="=";
			$query->where[1]["conditions"][1]["value"]=$user->uid;
		}
		
		
	}
	
	if($view->name=="taxonomy_term" && $view->current_display=="same_news") {
		$node=node_load(arg(1));
		if(is_object($node) && $node->type=="article" && isset($node->field_category["und"]) && $node->field_category["und"][0]["tid"]) {
			$query->where[1]["conditions"][1]["value"]=$node->field_category["und"][0]["tid"];
			$query->where[1]["conditions"][1]["operator"]="=";
			$query->where[1]["conditions"][2]["value"]=$node->nid;
		}
		//print_r($query);
//		unset($query->where[1]["conditions"][1]);
	}
//
}


function gumi_form_alter(&$form, &$form_state, $form_id) {
	
	
	
	
}

function gumi_form_submit(&$form, &$form_state) {
	//print_r($form);exit;
}


function gumi_node_insert($node) {
	
}

function gumi_user_insert(&$edit, $account, $category) {

}

