<?php


/**
 * Implements hook_menu().
 *
 * Defines a valid link to use when creating menu items.
 */
function menu_no_link_menu() {
  $items = array();
  $items['<hash>'] = array(
    'page callback' => 'drupal_not_found',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['<hash>/*'] = array(
    'page callback' => 'drupal_not_found',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_menu_link_alter().
 *
 * Flags the link to be altered at runtime.
 *
 * Note: Changes here would be saved back to the database.
 */
function menu_no_link_menu_link_alter(&$item, $menu) {
  if (strpos($item['link_path'], '<hash>') !== FALSE) {
    $item['options']['alter'] = TRUE;
  }
}

/**
 * Implements hook_translated_menu_link_alter().
 *
 * Refactors the link to go to the fragment #hash_link.
 */
function menu_no_link_translated_menu_link_alter(&$item, $map) {
  if (strpos($item['link_path'], '<hash>') !== FALSE) {
    $path = explode('/', $item['link_path']);
    $item['href'] = '';
    if (isset($path[1])) {
      $item['localized_options']['fragment'] = $path[1];
    }
    else {
      $item['localized_options']['fragment'] = ' ';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function menu_no_link_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "menu_edit_item") {
    $form['link_path']['#description'] = t('The path for this menu link.
       This can be an internal path such as %add-node or an external URL
       such as %example. Enter %front to link to the front page, %hash
       for no link and %hash_with_param for hash with param.',
        array(
          '%front' => '<front>',
          '%add-node' => 'node/add',
          '%example' => 'http://example.com',
          '%hash' => '<hash>',
          '%hash_with_param' => '<hash>/*',
        ));
  }
}